version: "3"
services:
  # DATABASE
  influxdb:
    image: "influxdb:latest"
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./packages/influxdb/volume:/var/lib/influxdb
  chronograf:
    image: "chronograf:latest"
    entrypoint: "chronograf --influxdb-url=http://influxdb:8086"
    ports:
      - 8888:8888
    depends_on:
      - influxdb

  # DASHBOARD
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - "./packages/grafana/volume:/var/lib/grafana"
      - "./packages/grafana/provisioning:/etc/grafana/provisioning"
      - "./packages/grafana/grafana.ini:/etc/grafana/grafana.ini"
    depends_on:
      - influxdb

  # lighthouse
  webperf-dashboard-lighthouse:
    image: "felicegeracitano/webperf-dashboard-lighthouse:1.1.1"
    ports:
      - 3000:3000
    environment:
      - HOST=influxdb
    volumes:
      - ./config.json:/usr/src/webperf-dashboard-lighthouse/config.json
    depends_on:
      - influxdb
