---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lighthouse-audit-job
spec:
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: lighthouse-audit-job
              image: ellerbrock/alpine-bash-curl-ssl
              command: ["bash", "-c"]
              args: [
                'set -x;
                 for i in "${URLS[@]}";
                  do curl -G ${LIGHTHOUSE_URL} \
                  --data-urlencode "url=${i}" \
                  --data-urlencode "mobile=${MOBILE}" \
                  --data-urlencode "userAgent=${USER_AGENT}" \
                  --data-urlencode "report=true" \
                  --data-urlencode "saveInDB=true";
                 done;
                ',
              ]
              env:
              - name: URLS
                value: {{ .Values.urls }}
              - name: MOBILE
                value: "true"
              - name: USER_AGENT
                value: {{ .Values.agent }}
              - name: LIGHTHOUSE_URL
                value: {{ .Values.audit_url }}
          restartPolicy: Never
