apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspector-wpt
  labels:
    app: inspector-wpt
spec:
  selector:
    matchLabels:
      app: inspector-wpt
  template:
    metadata:
      labels:
        app: inspector-wpt
    spec:
      containers:
        - name: inspector-wpt
          image: felicegeracitano/inspector-wpt:0.0.1
          ports:
            - containerPort: 3000
          resources:
          env:
            - name: DB_HOST
              value: influxdb
            - name: WPT_SERVER_HOST
              value: {{ .Values.wptServerHost }}
            - name: WPT_SERVER_URL_PORT
              value: {{ .Values.wptServerPort }}
